#!/usr/bin/env node
/**
 * build-docs.js
 *
 * Ingests the actual iX documentation from the docs/ directory and builds
 * a comprehensive docs.json for the chatbot RAG pipeline.
 *
 * Sources:
 *   1. docs/autogenerated/prompt/          — LLM-ready component API + code examples
 *   2. docs/components/<name>/guide.md     — component usage guides (design, UX)
 *   3. docs/components/overview.md         — component catalogue
 *   4. docs/home/                          — installation, getting-started, support, migration
 *   5. docs/guidelines/                    — accessibility, language, mobile, CLI, conversational
 *   6. docs/styles/                        — colors, typography, theming, borders, shadows
 *   7. docs/icons/                         — icon usage and development
 *   8. blog/                               — release notes, migration info, announcements
 *
 * Run:  node build-docs.js
 */

const fs = require("fs");
const path = require("path");

const REPO_ROOT = path.resolve(__dirname, "..");
const DOCS_ROOT = path.join(REPO_ROOT, "docs");
const BLOG_ROOT = path.join(REPO_ROOT, "blog");
const OUTPUT = path.resolve(__dirname, "docs.json");
const MAX_CHUNK_CHARS = 4000; // ≈ 1 000 tokens

// ─── URL mapping ────────────────────────────────────────────────────
const BASE_URL = "https://ix.siemens.io";

/** Map a source file path (relative to docs/) to an ix.siemens.io URL. */
function sourceToUrl(relPath) {
  if (!relPath) return null;

  // Blog posts
  if (relPath.startsWith("blog/")) {
    const slug = relPath.replace(/\/index\.md$/, "").replace(/^blog\//, "");
    return `${BASE_URL}/blog/${slug}`;
  }

  // autogenerated/prompt/ix-button/readme.md → /docs/components/button
  const promptMatch = relPath.match(/^autogenerated\/prompt\/ix-([^/]+)/);
  if (promptMatch) return `${BASE_URL}/docs/components/${promptMatch[1]}`;

  // components/<name>/guide.md → /docs/components/<name>
  const compMatch = relPath.match(/^components\/([^/]+)/);
  if (compMatch) return `${BASE_URL}/docs/components/${compMatch[1]}`;

  // home/installation/react.md → /docs/home/installation/react
  // guidelines/... , styles/... , icons/...
  const docPath = relPath
    .replace(/\/index\.mdx?$/, "")
    .replace(/\/overview\.mdx?$/, "")
    .replace(/\.mdx?$/, "");
  return `${BASE_URL}/docs/${docPath}`;
}

// ─── Helpers ────────────────────────────────────────────────────────

/** Recursively collect .md and .mdx files under `dir`. */
function readDirRecursive(dir, exts = [".md", ".mdx"]) {
  const results = [];
  if (!fs.existsSync(dir)) return results;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...readDirRecursive(full, exts));
    } else if (exts.some((e) => entry.name.endsWith(e))) {
      results.push(full);
    }
  }
  return results;
}

/** Strip YAML frontmatter delimited by --- ... --- */
function stripFrontmatter(content) {
  return content.replace(/^---[\s\S]*?---\n*/m, "");
}

/** Remove MDX-only syntax so we keep pure Markdown + code blocks. */
function cleanMdx(content) {
  let c = content;
  // Remove ES import lines (but not those inside code fences)
  c = c.replace(/^import\s+(?!['"]).*from\s+['"].*['"];?\s*$/gm, "");
  c = c.replace(/^import\s+['"].*['"];?\s*$/gm, "");
  // Remove JSX that wraps code-fence content but preserve the code fence content
  // Remove top-level JSX self-closing tags  <ComponentName ... />
  c = c.replace(/^<[A-Z][A-Za-z.]*(?:\s[^>]*)?\s*\/>$/gm, "");
  // Remove Docusaurus Tabs / TabItem wrappers but keep inner content
  c = c.replace(/<\/?Tabs[^>]*>/g, "");
  c = c.replace(/<\/?TabItem[^>]*>/g, "");
  // Remove Figma image links (they resolve to nothing outside the site)
  c = c.replace(/!\[.*?\]\(https:\/\/www\.figma\.com\/[^\)]+\)/g, "");
  // Collapse excessive blank lines
  c = c.replace(/\n{3,}/g, "\n\n");
  return c.trim();
}

/** Check if content is too sparse to be useful (mostly whitespace/empty code blocks). */
function isSubstantive(content) {
  const stripped = content.replace(/```[\s\S]*?```/g, "").replace(/\s+/g, " ").trim();
  // If after removing code blocks, there are fewer than 30 chars of prose,
  // but the content itself is under 100 chars total, skip it
  if (content.length < 100 && stripped.length < 30) return false;
  return true;
}

/** Derive a human-readable title from a file path. */
function titleFromPath(filePath, prefix = "") {
  const name = path.basename(filePath, path.extname(filePath));
  const pretty = name.replace(/[-_]/g, " ").replace(/\b\w/g, (ch) => ch.toUpperCase());
  return prefix ? `${prefix}: ${pretty}` : pretty;
}

// ─── Keyword extraction ─────────────────────────────────────────────

const STOPWORDS = new Set([
  "the","a","an","is","are","was","were","be","been","being","have","has",
  "had","do","does","did","will","would","could","should","may","might",
  "shall","can","need","dare","ought","used","to","of","in","for","on",
  "with","at","by","from","as","into","through","during","before","after",
  "above","below","between","out","off","over","under","again","further",
  "then","once","here","there","when","where","why","how","all","each",
  "every","both","few","more","most","other","some","such","no","nor",
  "not","only","own","same","so","than","too","very","and","but","or",
  "if","while","because","until","that","which","who","whom","this",
  "these","those","it","its","they","them","their","what","we","you",
  "your","i","me","my","he","she","his","her","up","about","just","also",
  "now","new","like","use","using","uses","see","e","g","etc","example",
  "following","set","default","true","false","type","string","boolean",
  "number","value","undefined","description","property","attribute",
  "returns","parameters","name","content","method","class","import",
  "export","const","let","var","function","return","html","head","body",
  "meta","charset","utf","link","rel","stylesheet","href","script","src",
  "title","div","span","module","app","component","selector","template",
]);

/**
 * Extract top-N keywords from title + content using term frequency.
 * Title words are triple-weighted; ix-* tags get a large boost.
 */
function extractKeywords(title, content) {
  const text = `${title} ${title} ${title} ${content}`.toLowerCase();
  const words = text.match(/[a-z][a-z0-9-]{1,}/g) || [];
  const freq = {};
  for (const w of words) {
    if (!STOPWORDS.has(w) && w.length > 2) {
      freq[w] = (freq[w] || 0) + 1;
    }
  }
  // Boost ix-* component tag names
  const ixTags = content.match(/ix-[a-z][a-z0-9-]*/g) || [];
  for (const tag of new Set(ixTags)) {
    freq[tag] = (freq[tag] || 0) + 10;
  }
  return Object.entries(freq)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 30)
    .map(([word]) => word);
}

// ─── Chunking ───────────────────────────────────────────────────────

/**
 * Split Markdown content into chunks at ## (H2) boundaries.
 * Chunks that are still too large are further split at ### (H3).
 */
function chunkByHeading(content, parentTitle) {
  const sections = content.split(/(?=^## )/m);
  const chunks = [];

  for (const section of sections) {
    if (!section.trim()) continue;
    const h2Match = section.match(/^##\s+(.+)/m);
    const sectionTitle = h2Match
      ? `${parentTitle} — ${h2Match[1].trim()}`
      : parentTitle;

    if (section.length <= MAX_CHUNK_CHARS) {
      chunks.push({ title: sectionTitle, content: section.trim() });
      continue;
    }

    // Sub-split at H3
    const subsections = section.split(/(?=^### )/m);
    for (const sub of subsections) {
      if (!sub.trim()) continue;
      const h3Match = sub.match(/^###\s+(.+)/m);
      const subTitle = h3Match
        ? `${sectionTitle} > ${h3Match[1].trim()}`
        : sectionTitle;
      // Hard-truncate if still huge (e.g. very long code examples)
      chunks.push({
        title: subTitle,
        content: sub.trim().slice(0, MAX_CHUNK_CHARS),
      });
    }
  }

  return chunks.length > 0 ? chunks : [{ title: parentTitle, content }];
}

// ─── Ingestion helpers ──────────────────────────────────────────────

function ingestFile(filePath, titlePrefix, allDocs, rootDir = DOCS_ROOT) {
  let raw = fs.readFileSync(filePath, "utf-8");
  raw = stripFrontmatter(raw);
  raw = cleanMdx(raw);
  if (raw.length < 50) return; // skip trivially empty

  const relPath = path.relative(rootDir, filePath).replace(/\\/g, "/");
  const source = rootDir === DOCS_ROOT ? relPath : `blog/${relPath}`;
  const url = sourceToUrl(source);
  const title = titleFromPath(filePath, titlePrefix);

  const chunks = raw.length > MAX_CHUNK_CHARS
    ? chunkByHeading(raw, title)
    : [{ title, content: raw }];

  for (const chunk of chunks) {
    if (chunk.content.length < 50) continue;
    if (!isSubstantive(chunk.content)) continue;
    allDocs.push({
      title: chunk.title,
      keywords: extractKeywords(chunk.title, chunk.content),
      content: chunk.content,
      source,
      url,
    });
  }
}

// ─── Main ───────────────────────────────────────────────────────────

const allDocs = [];

// 1️⃣  Component API + code examples  (autogenerated/prompt)
console.log("📖 Reading autogenerated prompt docs…");
const promptDir = path.join(DOCS_ROOT, "autogenerated", "prompt");
if (fs.existsSync(promptDir)) {
  for (const component of fs.readdirSync(promptDir, { withFileTypes: true })) {
    if (!component.isDirectory()) continue;
    const readmePath = path.join(promptDir, component.name, "readme.md");
    if (!fs.existsSync(readmePath)) continue;

    let raw = fs.readFileSync(readmePath, "utf-8");
    raw = stripFrontmatter(raw);
    raw = cleanMdx(raw);
    if (raw.length < 50) continue;

    const relPath = `autogenerated/prompt/${component.name}/readme.md`;
    const url = sourceToUrl(relPath);
    const chunks = chunkByHeading(raw, component.name);
    for (const chunk of chunks) {
      if (chunk.content.length < 50) continue;
      if (!isSubstantive(chunk.content)) continue;
      allDocs.push({
        title: chunk.title,
        keywords: extractKeywords(chunk.title, chunk.content),
        content: chunk.content,
        source: relPath,
        url,
      });
    }
  }
}

// 2️⃣  Component usage guides  (components/<name>/guide.md)
console.log("📖 Reading component usage guides…");
const componentsDir = path.join(DOCS_ROOT, "components");
if (fs.existsSync(componentsDir)) {
  for (const entry of fs.readdirSync(componentsDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const guidePath = path.join(componentsDir, entry.name, "guide.md");
    if (!fs.existsSync(guidePath)) continue;
    ingestFile(guidePath, `${entry.name} — Usage Guide`, allDocs);
  }
}

// 3️⃣  Components overview
const overviewPath = path.join(componentsDir, "overview.md");
if (fs.existsSync(overviewPath)) {
  ingestFile(overviewPath, "Components Overview", allDocs);
}

// 4️⃣  Home section  (installation, getting-started, support, releases, migration)
console.log("📖 Reading home docs…");
for (const f of readDirRecursive(path.join(DOCS_ROOT, "home"))) {
  ingestFile(f, "Home", allDocs);
}

// 5️⃣  Guidelines
console.log("📖 Reading guidelines…");
for (const f of readDirRecursive(path.join(DOCS_ROOT, "guidelines"))) {
  ingestFile(f, "Guidelines", allDocs);
}

// 6️⃣  Styles
console.log("📖 Reading styles…");
for (const f of readDirRecursive(path.join(DOCS_ROOT, "styles"))) {
  ingestFile(f, "Styles", allDocs);
}

// 7️⃣  Icons
console.log("📖 Reading icon docs…");
for (const f of readDirRecursive(path.join(DOCS_ROOT, "icons"))) {
  ingestFile(f, "Icons", allDocs);
}

// 8️⃣  Blog  (release notes, migration news, announcements)
console.log("📖 Reading blog posts…");
if (fs.existsSync(BLOG_ROOT)) {
  for (const f of readDirRecursive(BLOG_ROOT)) {
    ingestFile(f, "Blog", allDocs, BLOG_ROOT);
  }
}

// ─── Output ─────────────────────────────────────────────────────────

console.log(`\n✅  Generated ${allDocs.length} documentation chunks.`);

const sizeKB = (Buffer.byteLength(JSON.stringify(allDocs)) / 1024).toFixed(0);
console.log(`   Total size: ~${sizeKB} KB`);

fs.writeFileSync(OUTPUT, JSON.stringify(allDocs, null, 2), "utf-8");
console.log(`   Written to ${OUTPUT}`);
